# 🏠 House Prices - Advanced Regression Techniques
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data


## 📁 Описание файлов
| Файл | Описание |
|------|-------------|
| `train.csv` | Тренировочный набор данных |
| `test.csv` | Тестовый набор данных (без целевой переменной) |
| `data_description.txt` | Полное описание колонок (оригинал от Dean De Cock) |
| `sample_submission.csv` | Пример сабмита (бенчмарк на линейной регрессии) |

---

## 🎯 Целевая переменная
| Переменная | Описание |
|------------|----------|
| **SalePrice** | 💰 Цена продажи недвижимости в долларах *(целевая переменная, которую нужно предсказать)* |

---

## 📊 Поля данных

### 🏗 Характеристики здания
| Поле | Описание |
|------|----------|
| `MSSubClass` | Класс здания |
| `MSZoning` | Общая зональная классификация |
| `BldgType` | Тип жилого строения |
| `HouseStyle` | Стиль дома |
| `OverallQual` | Оценка качества материалов и отделки (1-10) |
| `OverallCond` | Общая оценка состояния (1-10) |
| `YearBuilt` | Год постройки |
| `YearRemodAdd` | Год последней реконструкции |
| `RoofStyle` | Тип крыши |
| `RoofMatl` | Материал крыши |
| `Exterior1st` | Внешняя отделка (основной материал) |
| `Exterior2nd` | Внешняя отделка (дополнительный материал) |
| `MasVnrType` | Тип каменной облицовки |
| `MasVnrArea` | Площадь каменной облицовки (кв. футы) |
| `ExterQual` | Качество внешних материалов |
| `ExterCond` | Текущее состояние внешних материалов |
| `Foundation` | Тип фундамента |

### 📏 Участок и земля
| Поле | Описание |
|------|----------|
| `LotFrontage` | Длина фасада вдоль улицы (линейные футы) |
| `LotArea` | Общая площадь участка (кв. футы) |
| `Street` | Тип доступа к дороге |
| `Alley` | Тип доступа к аллее |
| `LotShape` | Форма участка |
| `LandContour` | Рельеф участка |
| `Utilities` | Доступные коммуникации |
| `LotConfig` | Конфигурация участка |
| `LandSlope` | Уклон участка |

### 📍 Расположение и район
| Поле | Описание |
|------|----------|
| `Neighborhood` | Физическое расположение в черте города Ames |
| `Condition1` | Близость к главной дороге или ж/д путям |
| `Condition2` | Вторая близость (если применимо) |

### 🏠 Подвал
| Поле | Описание |
|------|----------|
| `BsmtQual` | Высота подвала |
| `BsmtCond` | Общее состояние подвала |
| `BsmtExposure` | Наличие выхода в сад/на улицу |
| `BsmtFinType1` | Качество отделки первой зоны подвала |
| `BsmtFinSF1` | Площадь отделки Type 1 (кв. футы) |
| `BsmtFinType2` | Качество отделки второй зоны (если есть) |
| `BsmtFinSF2` | Площадь отделки Type 2 (кв. футы) |
| `BsmtUnfSF` | Необработанная площадь подвала |
| `TotalBsmtSF` | **Общая площадь подвала** |

### 🔥 Отопление, кондиционирование и электрика
| Поле | Описание |
|------|----------|
| `Heating` | Тип отопления |
| `HeatingQC` | Качество и состояние отопления |
| `CentralAir` | Центральное кондиционирование (Y/N) |
| `Electrical` | Тип электрической системы |

### 📐 Внутренняя площадь
| Поле | Описание |
|------|----------|
| `1stFlrSF` | Площадь первого этажа |
| `2ndFlrSF` | Площадь второго этажа |
| `LowQualFinSF` | Площадь низкокачественной отделки (все этажи) |
| `GrLivArea` | **Жилая площадь над землёй** (кв. футы) |
| `FullBath` | Полные ванные комнаты над землёй |
| `HalfBath` | Половинные ванные над землёй |
| `BsmtFullBath` | Полные ванные в подвале |
| `BsmtHalfBath` | Половинные ванные в подвале |
| `Bedroom` | Количество спален над подвалом |
| `Kitchen` | Количество кухонь |
| `KitchenQual` | Качество кухни |
| `TotRmsAbvGrd` | Всего комнат над землёй (без ванных) |
| `Functional` | Рейтинг функциональности дома |

### 🔥 Камины и гараж
| Поле | Описание |
|------|----------|
| `Fireplaces` | Количество каминов |
| `FireplaceQu` | Качество каминов |
| `GarageType` | Расположение гаража |
| `GarageYrBlt` | Год постройки гаража |
| `GarageFinish` | Отделка интерьера гаража |
| `GarageCars` | Вместимость гаража (в машинах) |
| `GarageArea` | Площадь гаража (кв. футы) |
| `GarageQual` | Качество гаража |
| `GarageCond` | Состояние гаража |
| `PavedDrive` | Асфальтированный подъезд (Y/N) |

### 🌳 Внешние элементы
| Поле | Описание |
|------|----------|
| `WoodDeckSF` | Площадь деревянной террасы |
| `OpenPorchSF` | Площадь открытого крыльца |
| `EnclosedPorch` | Площадь закрытого крыльца |
| `3SsnPorch` | Площадь трёхсезонного крыльца |
| `ScreenPorch` | Площадь крыльца с москитной сеткой |
| `PoolArea` | Площадь бассейна |
| `PoolQC` | Качество бассейна |
| `Fence` | Качество забора |
| `MiscFeature` | Прочие особенности (не вошедшие в другие категории) |
| `MiscVal` | Стоимость прочих особенностей ($) |

### 📅 Информация о продаже
| Поле | Описание |
|------|----------|
| `MoSold` | Месяц продажи |
| `YrSold` | Год продажи |
| `SaleType` | Тип сделки |
| `SaleCondition` | Условия продажи |

---

> 💡 **Полезный совет:** 
> - Многие поля содержат пропуски (`NaN`) — это нормально (например, `PoolQC` отсутствует у большинства домов).
> - Категориальные признаки (тип данных `object`) потребуют кодирования перед обучением модели.
> - Начни с разведочного анализа данных (`df.describe()`, `df.info()`, визуализации распределений).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

train_df = pd.read_csv(r"C:\Users\ZiganshinShamil\Desktop\Study\Machine learning start\Решение проблем kaggle\Linear Regression\House Prices\House Prices dataset\train.csv", delimiter=',')
test_df = pd.read_csv(r"C:\Users\ZiganshinShamil\Desktop\Study\Machine learning start\Решение проблем kaggle\Linear Regression\House Prices\House Prices dataset\test.csv", delimiter=",")

print("Кол-во признаков в train: ", train_df.shape[1])
print("Кол-во строк в train: ", train_df.shape[0], "\n")

train_df.head(3)

Кол-во признаков в train:  81
Кол-во строк в train:  1460

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

#### Обработка данных

Удалим столбец id, так как он не нужен

In [42]:
train_df = train_df.drop("Id", axis=1)
train_df.head(3)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

Посмотрим типы столбцов

In [53]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   str
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   str
 5   Alley          91 non-null     str
 6   LotShape       1460 non-null   str
 7   LandContour    1460 non-null   str
 8   Utilities      1460 non-null   str
 9   LotConfig      1460 non-null   str
 10  LandSlope      1460 non-null   str
 11  Neighborhood   1460 non-null   str
 12  Condition1     1460 non-null   str
 13  Condition2     1460 non-null   str
 14  BldgType       1460 non-null   str
 15  HouseStyle     1460 non-null   str
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   str
 21  RoofMatl       1460 non-null   str
 22  Exterior1st    1460 non-null   str
 23  Exterior2nd    1460 non-null   str
 24  MasVnrType     588 non-null    str
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   str
 27  ExterCond      1460 non-null   str
 28  Foundation     1460 non-null   str
 29  BsmtQual       1423 non-null   str
 30  BsmtCond       1423 non-null   str
 31  BsmtExposure   1422 non-null   str
 32  BsmtFinType1   1423 non-null   str
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   str
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   str
 39  HeatingQC      1460 non-null   str
 40  CentralAir     1460 non-null   str
 41  Electrical     1459 non-null   str
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   str
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   str
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    str
 57  GarageType     1379 non-null   str
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   str
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   str
 63  GarageCond     1379 non-null   str
 64  PavedDrive     1460 non-null   str
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      str
 72  Fence          281 non-null    str
 73  MiscFeature    54 non-null     str
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   str
 78  SaleCondition  1460 non-null   str
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), str(43)
memory usage: 912.6 KB

Этот вывод df.info() — это медицинская карта датасета. Он говорит о трех главных вещах: структуре данных, проблемах с пропусками и типах данных, которые нужно исправить

In [ ]:
train_df["SalePrice"].describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64