In [11]:
import pandas as pd

df = pd.DataFrame({
    "Shamil": [21],
    "Kamil": [20],
    "Aidar": [19]
})
df

   Shamil  Kamil  Aidar
0      21     20     19

In [14]:
ds = pd.Series([1, 2, 3])
ds

0    1
1    2
2    3
dtype: int64

In [15]:
ds_copy = ds.copy()
ds_copy

0    1
1    2
2    3
dtype: int64

#### Добавление нового столбца
X.insert(loc, column, value)

In [21]:
df.insert(1, "alnert4", [2])
df

   alnert  alnert4  alnert2  Shamil  Kamil  Aidar
0       1        2        1      21     20     19

In [22]:
df = pd.DataFrame({
    "Shamil": [21, 177],
    "Kamil": [20, 177],
    "Aidar": [19, 196]
})
df

   Shamil  Kamil  Aidar
0      21     20     19
1     177    177    196

In [24]:
df.insert(0, "albert", [1, 2])

In [25]:
df

   albert  Shamil  Kamil  Aidar
0       1      21     20     19
1       2     177    177    196

#### Вытаскиваем данные из pd в формате np.array

In [27]:
X_mat = df.values
X_mat

array([[  1,  21,  20,  19],
       [  2, 177, 177, 196]])

#### Размеры dataframe

In [31]:
X_mat.shape

(2, 4)

#### Из numpy массива в DataFrame

In [2]:
from sklearn.datasets import load_iris
import pandas as pd
data = load_iris()

feature_names = data.keys()   # или data.feature_names
X = data.data
y = data.target

X = data.data
y = data.target
df_X = pd.DataFrame(X, columns=['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)'])
df_y = pd.Series(y)